version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: wellsync-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Ankur@123
      POSTGRES_DB: wellsync
    ports:
      - "5433:5432" # Mapped to 5433 so it doesn't conflict with local postgres
    volumes:
      - .db-data:/var/lib/postgresql/data
    restart: unless-stopped
